qdrant:
  host: "localhost"
  port: 6334

openAI:
  baseURL: "https://openrouter.ai/api/v1"
  apiKey: ""

temporal:
  hostPort: "localhost:7233"
  namespace: "default"

syncTemporal:
  hostPort: "localhost:7233"
  namespace: "CDC_SYNC_NAMESPACE"

mcpServer: "http://localhost:8085/mcp"

redis:
  addr: "localhost:6379"
  password: ""
  DB: 1

cdc:
  - addr: "localhost:58811"
    user: "root"
    password: ""
    dbName: "baoer"
    tableName:
      - "content_messages"
