qdrant:
  host: "localhost"
  port: 6334

openAI:
  baseURL: "https://openrouter.ai/api/v1"
  apiKey: ""

temporal:
  hostPort: "localhost:7233"
  namespace: "default"

syncTemporal:
  hostPort: "localhost:7233"
  namespace: "CDC_SYNC_NAMESPACE"

mcpServer: "http://localhost:8085/mcp"

redis:
  addr: "localhost:6379"
  password: ""
  DB: 1

fpMysql:
  host: "localhost"
  port: 3306
  userName: "root"
  password: "rootpassword"
  DB: "ivanka_content"

cdc:
  - addr: "localhost:3306"
    user: "root"
    password: "rootpassword"
    dbName: "ivanka_content"
    tableName:
      - "article_entries"
